spring:
  application:
    name: simple-quiz
  datasource:
    url: jdbc:postgresql://localhost:5432/simple-quiz
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 0
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/simple-quiz
    user: root
    password: root
    schemas: public
    locations:
      - classpath:db/migration

mybatis:
  mapper-locations: classpath*:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
knife4j:
  enable: true
  setting:
    language: zh_cn